### ISSUE TITLE
Questions on scale out design

### ISSUE THREAD

**Issue by Jeffwan** [CentaurusInfra/arktos#1012]
This project is awesome. Thanks for sharing! After reading [scale out design](https://github.com/CentaurusInfra/arktos/blob/master/docs/design-proposals/arch/arktos_scale_out.md), we still have some questions.

![image](https://user-images.githubusercontent.com/4739316/110189342-9f5a5180-7dd3-11eb-970d-984016033800.png)
> Note: In order to clarity questions clearly, I mark question number in above diagram

1. Any reason for controllers in resource manager to list and watch APIServer in tenant partitions? 

2. What's the purpose of scheduler in resource manager? I assume that's for cluster admins to deploy some cluster level tools?  

3. Currently, scheduler only schedule pods from APIServer in the same tenant partition. Schedulers between tenant partitions don't know each other. They all assume they own entire node pool and this may end up confliction. Have you considered to address this problem? 

4. From diagram [here](https://raw.githubusercontent.com/CentaurusInfra/arktos/master/docs/design-proposals/arch/images/scaleout_architecture.png) we know if the cluster is out of resource, we can add more `Resource Manager`.  What I am not sure is what the diagram will looks like? 

    Based on [component view diagram](https://github.com/CentaurusInfra/arktos/raw/master/docs/design-proposals/arch/images/scaleout_component.png),  does the existing tenant partition control plane components (like scheduler) connect to new new added resource manager? Or it's static partitioned? (resource manager only serves fixed number of tenant partitions?)

**Comment by wilsonwang371** [comment]
Adding one more question:

 In the architecture document, it is said there are one or more identical API Servers. Here in the diagram shown, it is listed as a single API Server. If multiple API Servers are used, are we also going to put another HAProxy in front of these identical API Servers?

**Comment by XiaoningDing** [comment]
Hello, here are my answers to the above questions (follow the question order):

1) This is because the node controller in resource manager needs to evict pods when a node is down. So the node controller needs to talk to tenant partitions to make pod-related updates.

2) This is to schedule the pods generated by DaemonSets. Infra operators will use daemonSet to deploy some per-host daemons, like network/storage/GPU plugins.  DaemonSet is disabled from tenant partitions because we don't allow end-user tenants to do this (a logical consequence of not allowing them to see hosts).

3) Yes, we have some thoughts and plans to reduce the probability of scheduler conflicts. Just haven't get resources to start working on that part.  (scheduling conflicts are always there when you have multi scheduler instances and they share a same global resource view.  It's not caused by partitioning itself.)    

4) It’s all dynamic and global resource view, not static partitioned. When a new resource manager is added, all existing tenant partitions will be aware of the change and connect to it based on the needs.  We’ve planned the feature but haven’t implemented it due to priorities. The general idea is to use CRD objects to represent tenant partitions and resource managers. It’s just a dynamic configuration management. Infra operators will update these CRD objects when a new partition is deployed, drained or retired.  

5) Yes, a tenant partition or a resource manager is usually deployed in a HA way and have multiple identical API servers.  Any load balancing mechanism can be used in front of these identical API server instances.

**Comment by Jeffwan** [comment]
Thanks for the clarification!
