### ISSUE TITLE
[service support] end-to-end verification of service in scale-out cluster

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1143]
**What would you like to be added**:
1. inside of pod
1. curl by service name

**Why is this needed**:
to ensure UX in scale-out env

**Comment by q131172019** [comment]
0. Set up 2 X 2 Scale-out environment in AWS using 4 X t2.2xlarge EC2 instances by following up the procedure at https://github.com/CentaurusInfra/arktos/blob/master/docs/setup-guide/scale-out-local-dev-setup.md

1. In scale-out environment you can not login into one pod  to use 'curl' to call one service due to the following error, which is caused by existing configuration. So we need use alternative way to  start one pod with init-container calling the service via curl to do our end-to-end tests.
```
$ cluster/kubectl.sh exec -ti pod/nginx-6567c8bff4-5pj6c -n default --tenant mytenant -- /bin/bash
Error from server (NotFound): pods "ip-172-31-13-237" not found
```

**Comment by q131172019** [comment]
HongWei and I verified the above procedure were working on 2021-09-28.

**Comment by q131172019** [comment]
I verified the above procedure was working again in 1 TP X 1 RP x (1 + 2) on 2021-11-20.

TP: ip-172-31-5-56

RP: 
master: ip-172-31-13-237
worker node: ip-172-31-26-244 and ip-172-31-29-26
