### ISSUE TITLE
update-vendor.sh got error: input contains a loop: tsort: k8s.io/client-go tsort: k8s.io/apiserver

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#884]
**What happened**:
when run update-vendor.sh, got error:
```
+++ [1219 01:46:05] go.mod: tidying
tsort: /tmp/update-vendor.jHjd/tidy_deps.txt: input contains a loop:
tsort: k8s.io/client-go
tsort: k8s.io/apiserver
```
Looks like it caused by this code in ./staging/src/k8s.io/client-go/discovery/discovery_client.go because this is the only k8s.io/apiserver under staging/src/k8s.io/client-go.
``` 
apifilters "k8s.io/apiserver/pkg/endpoints/filters"
```
**What you expected to happen**:
update-vendor run successfully
**How to reproduce it (as minimally and precisely as possible)**:
checkout to repro branch and run ./hack/update-vendor.sh, got this error.
**Anything else we need to know?**:
repro branch code: 
https://github.com/futurewei-cloud/arktos-perftest/commits/updatevendor-perf-20201210   
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chenqianfzh** [comment]
Please try out the latest  https://github.com/futurewei-cloud/arktos-perftest/commits/updatevendor-perf-20201210 with commit https://github.com/futurewei-cloud/arktos-perftest/commit/a822fc81b15de491c755ddf81e850817cb16d394.

The following result in my dev box showed the issue is fixed.

![image](https://user-images.githubusercontent.com/51831990/102815288-f928af00-4380-11eb-9ee0-a79b3f759476.png)

**Comment by sonyafenge** [comment]
fixed in this PR: https://github.com/CentaurusInfra/arktos/pull/892
